version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - CGO_ENABLED=0
      - GOOS=linux
    command: go run api/main.go
